# Generated by Django 6.0.2 on 2026-04-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_fa_method',
            field=models.CharField(choices=[('none', 'None'), ('totp', 'Authenticator App'), ('email', 'Email Code')], default='none', max_length=5),
        ),
    ]
