# Generated by Django 6.0.3 on 2026-04-07 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_property_latitude_property_longitude'),
        ('home', '0004_userprofile_two_fa_method'),
    ]

    operations = [
    ]
