# Generated by Django 6.0.3 on 2026-04-20 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_merge_20260406_2038'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('listing_type', models.CharField(blank=True, default='', max_length=20)),
                ('property_type', models.CharField(blank=True, default='', max_length=20)),
                ('budget', models.CharField(blank=True, default='', max_length=20)),
                ('amenity_filter', models.CharField(blank=True, default='', max_length=50)),
                ('sort_by', models.CharField(blank=True, default='', max_length=20)),
                ('keyword', models.CharField(blank=True, default='', max_length=200)),
                ('result_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='home_sh_user_created_idx'), models.Index(fields=['session_key', '-created_at'], name='home_sh_session_created_idx')],
            },
        ),
    ]
