# Generated by Django 6.0.3 on 2026-04-26 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userprofile_is_agent_verified_agentad_agentinquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentinquiry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Agent inquiries'},
        ),
    ]
