# Generated by Django 6.0.3 on 2026-04-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='inquirer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
